/* eslint-disable @next/next/no-img-element -- Owner-provided optimized portrait. */
import { PageHero } from "../../_components/page-hero";
import { PortfolioSection, PortfolioStats, RecordLinks } from "../../_components/portfolio";
import { SocialLinks } from "../../_components/social-links";
import { createFixedPageMetadata } from "../../_data/metadata";
import { publicContributions } from "../../_data/profiles";
import { FieldHighlights } from "../../_components/field-notes";
import { getFieldNote } from "../../_data/field-notes";
export const metadata = createFixedPageMetadata({ path: "/about/profile", title: "个人介绍｜闫哲祯 Zhezhen Yan", description: "从环境工程与数据分析到机器学习、强化学习与智能体工程，了解闫哲祯的研究经历、个人贡献和长期兴趣。" });
export default function ProfilePage() { return <main id="main-content" className="profile-page" tabIndex={-1}>
  <PageHero code="A1" eyebrow="PERSONAL PROFILE" breadcrumbs={[{ label: "首页", href: "/" }, { label: "关于", href: "/about" }, { label: "个人介绍" }]} title={<>闫哲祯<br /><span>Zhezhen Yan</span></>} description="同济大学环境科学与工程学院 · 资源与环境硕士。关注机器学习、强化学习与智能体工程，把模型、决策和可运行的软件连接起来。" tone="dark" density="detail" />
  <PortfolioSection id="profile-story" code="01 / MY PATH" title="从区域生态，走向工业过程"><div className="pf-portrait-layout"><div className="pf-prose"><p>我的专业起点是环境工程。2020 年进入大连理工大学后，我参与土地利用遥感分析和生物炭研究，并在本科毕业论文中完成了中国 30 个省份、2015—2019 年的生态足迹核算与时空分析。</p><p>这段训练让我学会把复杂资料整理成可计算的问题，也让我关注资源如何被使用、环境压力如何在不同地区分布。2024 年进入同济大学后，我开始把这种关注带到更加具体的工业过程。</p><p>在国家重点研发计划中，我承担铜电积的数据建模、解释分析和智能优化研究。我的第一作者论文已发表于《有色金属（冶炼部分）》；可解释安全强化学习研究处于 Journal of Cleaner Production 修回阶段，污水能耗预测研究正在 Water Environment Research 审稿。</p><p>工程实践是这条路径的另一部分。我参与生产数据与化验数据核验、MySQL 字段映射和系统联调，并将模型、优化和数值诊断连接为 CuLab 工作台，让研究结果可以被查看、比较与追溯。</p><p>我也在开源电商多智能体项目上补强售后可靠性，把审批、业务写入和结果核实连接起来。熟练使用 Coze、Codex、Claude Code、OpenCode、Hermes 等平台与开发工具，组织需求梳理、实现、调试与迭代。</p><p>持续关注大模型与智能体前沿，对预训练、后训练、模型微调和 RLHF 保持学习与理解，并把新的知识带回具体项目。</p></div><figure><img src="/images/profile/zhezhen-yan.webp" alt="闫哲祯的个人照片" width="640" height="893" loading="lazy" /><figcaption>同济大学 · 资源与环境硕士</figcaption></figure></div></PortfolioSection>
  <PortfolioSection id="profile-facts" code="02 / BACKGROUND" title="教育与能力"><PortfolioStats items={[{ value: "4.66 / 5", label: "硕士 GPA" }, { value: "89.59 / 100", label: "硕士平均成绩" }, { value: "CET-6", label: "英语；日语可进行日常交流" }, { value: "2027.06", label: "预计硕士毕业时间" }]} /><RecordLinks items={[{ label: "教育经历", href: "/education" }, { label: "技术能力与应用", href: "/skills" }, { label: "论文与报告", href: "/publications" }]} /></PortfolioSection>
  <PortfolioSection id="working-with-me" code="03 / WORKING WITH ME" title="把分析、协作与表达连接起来"><div className="pf-methods"><article><small>分析与实现</small><h3>沿着问题走到结果</h3><p>从数据和变量定义出发，完成建模、比较、解释与优化，再把结果组织为可使用的分析。</p></article><article><small>组织与协作</small><h3>在不同角色之间推进工作</h3><p>经历研究团队、企业与机关实习、学生组织和读者服务，能够配合不同工作方式，完成材料、任务与结果的衔接。</p></article><article><small>写作与传播</small><h3>让复杂内容容易被理解</h3><p>既写研究论文与技术说明，也参与脚本、摄影、剪辑和校园融媒体，用合适的形式表达具体内容。</p></article><article><small>持续学习</small><h3>把问题带回工具与社区</h3><p>持续使用和研究开源工具，也在 LangChain 项目反馈过 ChatDeepSeek 多轮工具调用中的 reasoning_content 兼容问题。</p><RecordLinks items={[{ label: "GitHub Issue #37713", href: publicContributions[0].href }]} /></article></div></PortfolioSection>
  <PortfolioSection id="beyond-research" code="04 / BEYOND RESEARCH" title="天文、长跑、镜头与现场"><div className="pf-prose"><p>我喜欢长跑，曾入选大连理工大学定向越野校队；也喜欢乒乓球、摄影和视频表达。科幻读书分享和多年动画记录，让我保留对故事、技术和不同生活的好奇。</p><p>兴趣也把我带到了现场：去佘山和上海天文馆看观测设备与航天展陈，沿着西湖走一整圈，在青岛的海边拍照。第一次演唱会留给了从大一就开始听的 milet；在鸣潮音乐会，熟悉的旋律又成为了可以共同唱出来的记忆。</p><p>本科期间在阳光心理健康协会和校园传播团队的工作，以及硕士期间的图书馆与班级服务，是我理解协作和公共表达的重要经历。记录、参与和表达，一直贯穿在研究与生活之间。</p></div><FieldHighlights notes={[getFieldNote("astronomy-and-dishui"), getFieldNote("qingdao-coast"), getFieldNote("milet-first-live")]} /><RecordLinks items={[{ label: "科研与实践经历", href: "/experience" }, { label: "生活记录", href: "/life" }, { label: "游戏足迹", href: "/life/gaming" }, { label: "个人随想", href: "/thoughts" }]} /><SocialLinks variant="editorial" /></PortfolioSection>
</main>; }
